name: Build & Push to DockerHub, ACR, ECR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: python-demo
      TAG: latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # ------------------------
      # Docker Hub Login
      # ------------------------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ------------------------
      # Azure Login & ACR Login
      # ------------------------
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Login to Azure ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      # ------------------------
      # AWS Login & ECR Login
      # ------------------------
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # ------------------------
      # Build Image Once
      # ------------------------
      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$TAG .

      # ------------------------
      # Tag Images
      # ------------------------
      - name: Tag Images
        run: |
          docker tag $IMAGE_NAME:$TAG ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$TAG
          docker tag $IMAGE_NAME:$TAG ${{ secrets.ACR_NAME }}.azurecr.io/$IMAGE_NAME:$TAG
          docker tag $IMAGE_NAME:$TAG \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$TAG

      # ------------------------
      # Push Images
      # ------------------------
      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$TAG

      - name: Push to Azure ACR
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/$IMAGE_NAME:$TAG

      - name: Push to AWS ECR
        run: |
          docker push \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$TAG
